# Use an official Python runtime as a parent image
FROM python:3.8.11-slim

# Set the working directory in the container to /app
WORKDIR /app

# Update the base image
RUN apt-get update -qq

# Install dependencies
RUN apt-get install -y --fix-missing \
    python3-pip \
    python3-dev \
    build-essential

RUN pip install poetry

# Copy app files
COPY . .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# RUN poetry config virtualenvs.create false
RUN poetry run pip install -U pip
RUN poetry install --no-interaction --no-ansi

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD streamlit run app.py

